project: 
  type: website
  resources: 
    - "google104c65d255c80fff.html"
    - lebanon-slides.pdf
  output-dir: docs

website:
  search: false
  navbar:
    title: false
    left:
      - href: index.qmd
        text: About me
      - href: research.qmd
        text: My research
  page-footer:
    left: © 2025 Lennard Naumann
  
format:
  html:
    theme: 
      light: 
        - flatly
        - custom_theming.css
      dark: 
        - darkly
        - custom_theming.css
    toc: true
    page-layout: full

editor: visual

