project: 
  type: website
  resources: 
    - "google104c65d255c80fff.html"
    - slides.html
  output-dir: docs

title: Lennard Naumann
subtitle: |
  PhD Researcher \
  WZB Berlin Social Science Center \
  DYNAMICS Research Training Group \
  [lennard.naumann@wzb.eu](mailto:lennard.naumann@wzb.eu)

description-meta: "Lennard Naumann Academic Website"
author-meta: "Lennard Naumann"

website:
  title: "Lennard Naumann"
  description: "Lennard Naumann's Academic Website"
  search: false
  navbar: false
  page-footer:
    left: © 2026 Lennard Naumann
  
format:
  html:
    theme: cosmo
    css: custom_theming.css
    footnotes-hover: true
    code-copy: true
    code-link: true
    code-overflow: wrap
    fig-align: center
    link-external-icon: false
    link-external-newwindow: true
    email-obfuscation: javascript
    link-external-filter: '^(?:http:|https:)\/\/drganghe\.github\.io\/custom'
