project:
  type: website
  output-dir: docs

website:
  title: "Lennard Naumann"
  search: false
  navbar:
    left:
      - href: index.qmd
        text: Home
format:
  html:
    theme: 
      light: [flatly, custom_theming.scss]
      dark: [darkly, custom_theming.scss]
    toc: true
    page-layout: full

editor: visual

