project:
  type: website
  output-dir: docs

website:
  title: "Lennard Naumann"
  search: false
  navbar:
    left:
      - href: index.qmd
        text: Home
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    page-layout: full

editor: visual

