project:
  type: website
  resources: "google104c65d255c80fff.html"
  output-dir: docs

website:
  title: "Lennard Naumann"
  search: false
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: research.qmd
        text: Research
  page-footer:
    left: © 2025 Lennard Naumann
  
format:
  html:
    theme: 
      light: 
        - flatly
        - custom_theming.css
      dark: 
        - darkly
        - custom_theming.css
    toc: true
    page-layout: full

editor: visual

